from __future__ import annotations

import re
from datetime import datetime, timezone
from decimal import Decimal

from sqlalchemy.orm import Session

from app.models.company_profile import CompanyProfile
from app.models.employee import Employee
from app.models.payroll_t4 import PayrollT4
from app.services.payroll_t4_storage_service import (
    build_db_backed_t4_storage_key,
    clear_t4_slip_artifact,
    load_t4_slip_artifact,
    store_t4_slip_artifact,
)


def _sanitize_segment(value: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9._-]+", "-", str(value or "").strip())
    return cleaned.strip("-") or "value"


def _format_cents(value: int) -> str:
    cents = int(value or 0)
    dollars = Decimal(cents) / Decimal("100")
    return f"${dollars:,.2f}"


def _pdf_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")


def _build_simple_pdf(lines: list[str]) -> bytes:
    content_lines = ["BT", "/F1 12 Tf", "72 750 Td", "16 TL"]
    for index, line in enumerate(lines):
        escaped = _pdf_escape(line)
        if index == 0:
            content_lines.append(f"({escaped}) Tj")
        else:
            content_lines.append(f"T* ({escaped}) Tj")
    content_lines.append("ET")
    content_stream = "\n".join(content_lines).encode("utf-8")

    objects: list[bytes] = []
    objects.append(b"1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj\n")
    objects.append(b"2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj\n")
    objects.append(
        b"3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
        b"/Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >> endobj\n"
    )
    objects.append(
        b"4 0 obj << /Length "
        + str(len(content_stream)).encode("ascii")
        + b" >> stream\n"
        + content_stream
        + b"\nendstream endobj\n"
    )
    objects.append(b"5 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj\n")

    header = b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n"
    chunks = [header]
    offsets = [0]
    current = len(header)
    for obj in objects:
        offsets.append(current)
        chunks.append(obj)
        current += len(obj)

    xref_offset = current
    xref = [f"xref\n0 {len(offsets)}\n".encode("ascii"), b"0000000000 65535 f \n"]
    for offset in offsets[1:]:
        xref.append(f"{offset:010d} 00000 n \n".encode("ascii"))
    trailer = (
        f"trailer << /Size {len(offsets)} /Root 1 0 R >>\nstartxref\n{xref_offset}\n%%EOF\n".encode("ascii")
    )
    return b"".join(chunks + xref + [trailer])


def _build_t4_pdf(*, company_name: str, employee_name: str, tax_year: int, payroll_t4: PayrollT4) -> bytes:
    lines = [
        f"T4 Statement of Remuneration Paid - {int(tax_year)}",
        f"Company: {company_name}",
        f"Employee: {employee_name}",
        f"T4 ID: {payroll_t4.t4_id}",
        "",
        f"Employment income: {_format_cents(int(payroll_t4.employment_income_cents))}",
        f"CPP contributions: {_format_cents(int(payroll_t4.cpp_contributions_cents))}",
        f"EI premiums: {_format_cents(int(payroll_t4.ei_premiums_cents))}",
        f"Income tax deducted: {_format_cents(int(payroll_t4.income_tax_deducted_cents))}",
        f"Other deductions: {_format_cents(int(payroll_t4.other_deductions_cents))}",
        "",
        "Generated by Frontier payroll output workflow.",
    ]
    return _build_simple_pdf(lines)


def invalidate_t4_slip(payroll_t4: PayrollT4) -> None:
    payroll_t4.slip_status = "RECORD_ONLY"
    clear_t4_slip_artifact(payroll_t4)
    payroll_t4.slip_generated_at = None
    payroll_t4.slip_generated_by_user_id = None
    payroll_t4.slip_available_at = None
    payroll_t4.delivery_status = "PENDING_MANUAL"
    payroll_t4.delivered_at = None
    payroll_t4.delivered_by_user_id = None
    payroll_t4.slip_download_count = 0
    payroll_t4.slip_last_downloaded_at = None
    payroll_t4.slip_last_downloaded_by_user_id = None
    payroll_t4.employee_download_count = 0
    payroll_t4.employee_first_downloaded_at = None
    payroll_t4.employee_last_downloaded_at = None
    payroll_t4.employee_last_downloaded_by_user_id = None
    payroll_t4.employee_acknowledged_at = None
    payroll_t4.employee_acknowledged_by_user_id = None


def generate_t4_slips_for_tax_year(*, db: Session, company_id: int, tax_year: int, actor_user_id: str | None) -> dict[str, int]:
    company = (
        db.query(CompanyProfile)
        .filter(CompanyProfile.company_id == int(company_id))
        .one_or_none()
    )
    if company is None:
        raise ValueError("CompanyProfile not found")

    rows = (
        db.query(PayrollT4, Employee)
        .join(
            Employee,
            (Employee.company_id == PayrollT4.company_id) & (Employee.id == PayrollT4.employee_id),
        )
        .filter(PayrollT4.company_id == int(company_id))
        .filter(PayrollT4.tax_year == int(tax_year))
        .order_by(PayrollT4.employee_id.asc(), PayrollT4.t4_id.asc())
        .all()
    )

    generated = 0
    regenerated = 0
    now = datetime.now(timezone.utc)
    company_slug = _sanitize_segment(str(company.company_name))

    for payroll_t4, employee in rows:
        employee_name = str(employee.legal_name or employee.name or f"Employee {int(employee.id)}")
        employee_slug = _sanitize_segment(employee_name)
        file_name = f"t4-{int(tax_year)}-{company_slug}-{employee_slug}.pdf"
        blob = _build_t4_pdf(
            company_name=str(company.company_name),
            employee_name=employee_name,
            tax_year=int(tax_year),
            payroll_t4=payroll_t4,
        )
        was_available = str(payroll_t4.slip_status) == "AVAILABLE" and load_t4_slip_artifact(payroll_t4) is not None

        invalidate_t4_slip(payroll_t4)
        artifact = store_t4_slip_artifact(
            payroll_t4,
            storage_key=build_db_backed_t4_storage_key(
                company_id=int(company_id),
                t4_id=str(payroll_t4.t4_id),
                file_name=file_name,
            ),
            file_name=file_name,
            content_type="application/pdf",
            blob=blob,
        )

        payroll_t4.slip_status = "AVAILABLE"
        payroll_t4.slip_generated_at = now
        payroll_t4.slip_generated_by_user_id = actor_user_id
        payroll_t4.slip_available_at = now
        payroll_t4.slip_file_name = artifact.file_name

        if was_available:
            regenerated += 1
        else:
            generated += 1

    return {
        "tax_year": int(tax_year),
        "generated": generated,
        "regenerated": regenerated,
    }


def mark_t4_downloaded(payroll_t4: PayrollT4, *, actor_user_id: str | None) -> None:
    payroll_t4.slip_download_count = int(payroll_t4.slip_download_count or 0) + 1
    payroll_t4.slip_last_downloaded_at = datetime.now(timezone.utc)
    payroll_t4.slip_last_downloaded_by_user_id = actor_user_id


def mark_t4_delivered_manually(payroll_t4: PayrollT4, *, actor_user_id: str | None) -> None:
    now = datetime.now(timezone.utc)
    payroll_t4.delivery_status = "DELIVERED_MANUAL"
    payroll_t4.delivered_at = now
    payroll_t4.delivered_by_user_id = actor_user_id


def mark_t4_employee_downloaded(payroll_t4: PayrollT4, *, actor_user_id: str | None) -> None:
    now = datetime.now(timezone.utc)
    mark_t4_downloaded(payroll_t4, actor_user_id=actor_user_id)
    payroll_t4.employee_download_count = int(payroll_t4.employee_download_count or 0) + 1
    if payroll_t4.employee_first_downloaded_at is None:
        payroll_t4.employee_first_downloaded_at = now
    payroll_t4.employee_last_downloaded_at = now
    payroll_t4.employee_last_downloaded_by_user_id = actor_user_id


def acknowledge_t4_employee_access(payroll_t4: PayrollT4, *, actor_user_id: str | None) -> None:
    if payroll_t4.employee_acknowledged_at is not None:
        return
    payroll_t4.employee_acknowledged_at = datetime.now(timezone.utc)
    payroll_t4.employee_acknowledged_by_user_id = actor_user_id
