"""initial_schema

Revision ID: c4d09a62d3c6
Revises: e907a918b237
Create Date: 2026-02-19 16:41:44.279692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4d09a62d3c6'
down_revision: Union[str, Sequence[str], None] = 'e907a918b237'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_cost_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('scope_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_reference_id', sa.String(), nullable=False),
    sa.Column('cost_category', sa.String(), nullable=False),
    sa.Column('quantity', sa.Numeric(), nullable=True),
    sa.Column('unit_cost_cents', sa.Integer(), nullable=True),
    sa.Column('total_cost_cents', sa.Integer(), nullable=False),
    sa.Column('posting_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('immutable_flag', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'source_type', 'source_reference_id', 'cost_category', name='uq_job_cost_ledger_posting_key')
    )
    op.create_index(op.f('ix_job_cost_ledger_company_id'), 'job_cost_ledger', ['company_id'], unique=False)
    op.create_index(op.f('ix_job_cost_ledger_cost_category'), 'job_cost_ledger', ['cost_category'], unique=False)
    op.create_index(op.f('ix_job_cost_ledger_employee_id'), 'job_cost_ledger', ['employee_id'], unique=False)
    op.create_index(op.f('ix_job_cost_ledger_id'), 'job_cost_ledger', ['id'], unique=False)
    op.create_index(op.f('ix_job_cost_ledger_job_id'), 'job_cost_ledger', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_cost_ledger_posting_date'), 'job_cost_ledger', ['posting_date'], unique=False)
    op.create_index(op.f('ix_job_cost_ledger_scope_id'), 'job_cost_ledger', ['scope_id'], unique=False)
    op.create_index(op.f('ix_job_cost_ledger_source_reference_id'), 'job_cost_ledger', ['source_reference_id'], unique=False)
    op.create_index(op.f('ix_job_cost_ledger_source_type'), 'job_cost_ledger', ['source_type'], unique=False)
    op.create_table('pay_period',
    sa.Column('pay_period_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('start_date < end_date', name='ck_pay_period_start_before_end'),
    sa.PrimaryKeyConstraint('pay_period_id')
    )
    op.create_index(op.f('ix_pay_period_company_id'), 'pay_period', ['company_id'], unique=False)
    op.create_table('time_entries',
    sa.Column('time_entry_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('scope_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('time_entry_id')
    )
    op.create_index(op.f('ix_time_entries_company_id'), 'time_entries', ['company_id'], unique=False)
    op.create_index(op.f('ix_time_entries_employee_id'), 'time_entries', ['employee_id'], unique=False)
    op.create_index(op.f('ix_time_entries_job_id'), 'time_entries', ['job_id'], unique=False)
    op.create_index(op.f('ix_time_entries_scope_id'), 'time_entries', ['scope_id'], unique=False)
    op.create_index(op.f('ix_time_entries_status'), 'time_entries', ['status'], unique=False)
    op.create_index(op.f('ix_time_entries_time_entry_id'), 'time_entries', ['time_entry_id'], unique=False)
    op.create_table('workflow_executions',
    sa.Column('execution_id', sa.String(), nullable=False),
    sa.Column('flow_name', sa.String(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_step_id', sa.String(), nullable=True),
    sa.Column('completed_steps', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('execution_id')
    )
    op.create_index(op.f('ix_workflow_executions_execution_id'), 'workflow_executions', ['execution_id'], unique=False)
    op.create_table('payroll_run',
    sa.Column('payroll_run_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('pay_period_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pay_period_id'], ['pay_period.pay_period_id'], ),
    sa.PrimaryKeyConstraint('payroll_run_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payroll_run')
    op.drop_index(op.f('ix_workflow_executions_execution_id'), table_name='workflow_executions')
    op.drop_table('workflow_executions')
    op.drop_index(op.f('ix_time_entries_time_entry_id'), table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_status'), table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_scope_id'), table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_job_id'), table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_employee_id'), table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_company_id'), table_name='time_entries')
    op.drop_table('time_entries')
    op.drop_index(op.f('ix_pay_period_company_id'), table_name='pay_period')
    op.drop_table('pay_period')
    op.drop_index(op.f('ix_job_cost_ledger_source_type'), table_name='job_cost_ledger')
    op.drop_index(op.f('ix_job_cost_ledger_source_reference_id'), table_name='job_cost_ledger')
    op.drop_index(op.f('ix_job_cost_ledger_scope_id'), table_name='job_cost_ledger')
    op.drop_index(op.f('ix_job_cost_ledger_posting_date'), table_name='job_cost_ledger')
    op.drop_index(op.f('ix_job_cost_ledger_job_id'), table_name='job_cost_ledger')
    op.drop_index(op.f('ix_job_cost_ledger_id'), table_name='job_cost_ledger')
    op.drop_index(op.f('ix_job_cost_ledger_employee_id'), table_name='job_cost_ledger')
    op.drop_index(op.f('ix_job_cost_ledger_cost_category'), table_name='job_cost_ledger')
    op.drop_index(op.f('ix_job_cost_ledger_company_id'), table_name='job_cost_ledger')
    op.drop_table('job_cost_ledger')
    # ### end Alembic commands ###
