"""add payroll domain

Revision ID: e907a918b237
Revises: 2f5c6b9733b3
Create Date: 2026-02-19 15:24:07.932156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e907a918b237'
down_revision: Union[str, Sequence[str], None] = '2f5c6b9733b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_time_entries_company_id")
    op.execute("DROP INDEX IF EXISTS ix_time_entries_employee_id")
    op.execute("DROP INDEX IF EXISTS ix_time_entries_status")
    op.execute("DROP INDEX IF EXISTS ix_time_entries_time_entry_id")
    op.execute("DROP TABLE IF EXISTS time_entries CASCADE")
    op.execute("DROP INDEX IF EXISTS ix_payroll_items_id")
    op.execute("DROP TABLE IF EXISTS payroll_items CASCADE")
    op.execute("DROP INDEX IF EXISTS ix_employees_employee_number")
    op.execute("DROP INDEX IF EXISTS ix_employees_id")
    op.execute("DROP TABLE IF EXISTS employees CASCADE")
    op.execute("DROP INDEX IF EXISTS ix_sites_id")
    op.execute("DROP TABLE IF EXISTS sites CASCADE")
    op.execute("DROP INDEX IF EXISTS ix_jobs_id")
    op.execute("DROP TABLE IF EXISTS jobs CASCADE")
    op.execute("DROP INDEX IF EXISTS ix_payroll_runs_id")
    op.execute("DROP TABLE IF EXISTS payroll_runs CASCADE")
    op.execute("DROP INDEX IF EXISTS ix_job_cost_ledger_company_id")
    op.execute("DROP INDEX IF EXISTS ix_job_cost_ledger_cost_category")
    op.execute("DROP INDEX IF EXISTS ix_job_cost_ledger_employee_id")
    op.execute("DROP INDEX IF EXISTS ix_job_cost_ledger_id")
    op.execute("DROP INDEX IF EXISTS ix_job_cost_ledger_job_id")
    op.execute("DROP INDEX IF EXISTS ix_job_cost_ledger_posting_date")
    op.execute("DROP INDEX IF EXISTS ix_job_cost_ledger_scope_id")
    op.execute("DROP INDEX IF EXISTS ix_job_cost_ledger_source_reference_id")
    op.execute("DROP INDEX IF EXISTS ix_job_cost_ledger_source_type")
    op.execute("DROP TABLE IF EXISTS job_cost_ledger CASCADE")
    op.execute("DROP INDEX IF EXISTS ix_workflow_executions_execution_id")
    op.execute("DROP TABLE IF EXISTS workflow_executions CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_executions',
    sa.Column('execution_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('flow_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('context', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('current_step_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('completed_steps', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('execution_id', name=op.f('workflow_executions_pkey'))
    )
    op.create_index(op.f('ix_workflow_executions_execution_id'), 'workflow_executions', ['execution_id'], unique=False)
    op.create_table('job_cost_ledger',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('scope_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('source_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('source_reference_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cost_category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('unit_cost_cents', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_cost_cents', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('posting_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('immutable_flag', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('job_cost_ledger_pkey')),
    sa.UniqueConstraint('company_id', 'source_type', 'source_reference_id', 'cost_category', name=op.f('uq_job_cost_ledger_posting_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_job_cost_ledger_source_type'), 'job_cost_ledger', ['source_type'], unique=False)
    op.create_index(op.f('ix_job_cost_ledger_source_reference_id'), 'job_cost_ledger', ['source_reference_id'], unique=False)
    op.create_index(op.f('ix_job_cost_ledger_scope_id'), 'job_cost_ledger', ['scope_id'], unique=False)
    op.create_index(op.f('ix_job_cost_ledger_posting_date'), 'job_cost_ledger', ['posting_date'], unique=False)
    op.create_index(op.f('ix_job_cost_ledger_job_id'), 'job_cost_ledger', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_cost_ledger_id'), 'job_cost_ledger', ['id'], unique=False)
    op.create_index(op.f('ix_job_cost_ledger_employee_id'), 'job_cost_ledger', ['employee_id'], unique=False)
    op.create_index(op.f('ix_job_cost_ledger_cost_category'), 'job_cost_ledger', ['cost_category'], unique=False)
    op.create_index(op.f('ix_job_cost_ledger_company_id'), 'job_cost_ledger', ['company_id'], unique=False)
    op.create_table('payroll_runs',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('payroll_runs_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('total_hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_gross_pay', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_net_pay', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_source_deductions', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('approved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('paid_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='payroll_runs_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_payroll_runs_id'), 'payroll_runs', ['id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('jobs_pkey'))
    )
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_table('sites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('sites_pkey'))
    )
    op.create_index(op.f('ix_sites_id'), 'sites', ['id'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('employees_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('employee_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pin_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pay_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hourly_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('salary_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('vacation_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('pay_period', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pay_day', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cutoff_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('overtime_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('overtime_daily_hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('overtime_weekly_hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('overtime_multiplier', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('benefits_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('benefits_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='employees_pkey'),
    sa.UniqueConstraint('email', name='employees_email_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_index(op.f('ix_employees_employee_number'), 'employees', ['employee_number'], unique=True)
    op.create_table('payroll_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('payroll_run_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('gross_pay', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('benefits_deduction', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cpp_deduction', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ei_deduction', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('tax_deduction', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_deductions', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('net_pay', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('employer_cpp', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('employer_ei', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('source_deductions_total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('paid', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('payroll_items_employee_id_fkey')),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payroll_runs.id'], name=op.f('payroll_items_payroll_run_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('payroll_items_pkey'))
    )
    op.create_index(op.f('ix_payroll_items_id'), 'payroll_items', ['id'], unique=False)
    op.create_table('time_entries',
    sa.Column('time_entry_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('scope_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('ended_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('time_entry_id', name=op.f('time_entries_pkey'))
    )
    op.create_index(op.f('ix_time_entries_time_entry_id'), 'time_entries', ['time_entry_id'], unique=False)
    op.create_index(op.f('ix_time_entries_status'), 'time_entries', ['status'], unique=False)
    op.create_index(op.f('ix_time_entries_employee_id'), 'time_entries', ['employee_id'], unique=False)
    op.create_index(op.f('ix_time_entries_company_id'), 'time_entries', ['company_id'], unique=False)
    # ### end Alembic commands ###
